### ISSUE TITLE
Directories/data not found in the Age2HD folder 

### ISSUE THREAD

**Issue by ArbitRandomUser** [glouw/openempires#1]
i tried to clone repo and compile ,compilation succeeded but i could not find the /home/user/.steam/steam/steamapps/common/Age2HD/Directory/data/ , 
infact there is no dir Directory inside Age2HD

**Comment by glouw** [comment]
strange. have a poke around. you're looking for a data folder holding these files: interfac.drs, terrain.drs, graphics.drs, and blendomatic.dat.

**Comment by ArbitRandomUser** [comment]
i poked around a bit and found that Age2HD/resources/_common contains a folder drs/ , however drs/ does not contain any .drs files but more subfolders gamedata_x1/  gamedata_x2/  graphics/  interface/  retail-campaigns/  sounds/ with many .slp , .wav , .per etc files in them , instead of the old  drs files as data format they have been unpacked and placed in these directories

**Comment by glouw** [comment]
ah, strange, it must've been left there from the compatibility patch i used to play on voobly. for now the *.drs files above will need to be loaded from the actual boxed set until i figure out how to load the HD assets.

**Comment by ludvigknutsmark** [comment]
Any updates on this?

**Comment by glouw** [comment]
for now, HD is not directly supported, so meanwhile, please use the Age2HD Voobly compatibility patch found here: http://aoccs.net/

**Comment by glouw** [comment]
however, I will have HD file loading support ready in the next 3-4 weeks

**Comment by sandsmark** [comment]
fwiw: aoe2hd does not use drs files, it just has all the content "unpacked", you can see all the differences here (sorry, not the cleanest code): https://github.com/sandsmark/freeaoe/blob/master/src/resource/AssetManager_HD.h

in addition, the latest version of aoe2hd (Rise of the Rajas) does not ship the terrain SLP files at all, hence https://github.com/sandsmark/freeaoe/blob/master/src/resource/AssetManager_HD.h#L159 + https://github.com/sandsmark/freeaoe/blob/master/src/ui/HomeScreen.cpp#L75 (also explains how to get the correct version in steam).

edit: and fwiw, aoe2hd ships the terrain graphics as PNGs, I started on support for them in freeaoe but it's a pain. My last idea before I gave up was to just use the code I have in genieutils to convert from RGB to indexed SLP to try to recreate the SLPs and use the normal code for blending and lighting, but then I first need to transform them etc...

So for now I'd recommend just ignoring HD, or at least Rise of the Rajas and later.

Oh, and DE only ships them as directx textures, but using pngs or dds files as source shouldn't be that different.

**Comment by glouw** [comment]
Good to hear from you again sands.

There are so many age2 variants today that supporting the base game is probably our best bet. Finding an original age2 copy is not hard. Heck, I found the gold edition at my thrift store for $2.

I do have a rough idea of how to pack the HD contents into a DRS/SLP format. I am currently ironing out the last of some major networking issues, and I will probably tackle HD asset support next, or at least after I add a few more units and tech for some sort of base game.

**Comment by sandsmark** [comment]
> Finding an original age2 copy is not hard.

What I do for automated testing is to just download the trial version from archive.org, it doesn't have everything (missing higher res UI etc.) but enough for basic play testing: https://archive.org/details/AgeOfEmpiresIiTheConquerorsDemo

edit; and just in case you haven't looked at it, using the inverse color maps (icm files), it's pretty trivial to convert from normal RGB images to SLP files. Here's the code I wrote for importing PNGs to SLPs in AGE: https://github.com/sandsmark/AGE/blob/master/AGE_Frame/Other.cpp#L3704-L3720

**Comment by glouw** [comment]
ah wonderful, AGE_Frame::BitmapToSLP is so simple. Will work great for the terrain. I may port it to save time.

**Comment by glouw** [comment]
Hey all, I've seriously considered sandsmark's trial idea, and I have opted to switch this engine to use the trial demo assets. You can find it on fileplanet and the likes (https://www.fileplanet.com/archive/p-51605/Age-of-Empires-II-Age-of-Kings-Demo).

As this data set only includes western European sprites, I am going to limit the gameplay to Britons, Celts, and Franks (the trial assets include cavaliers!), and limit the ages to Dark, Feudal, and Castle ages.

This will greatly simplify a lot of the code, and still provide a reasonable multiplayer experience.

In closing, I am sad to say that there no longer is a true reference point for the original assets. HD has hacked up the assets so much that it requires a converter to be written to pack the sprites into a DRS / SLP package, and even if that were done, a faulty mod may move pixels and cause the strangest out of sync bugs. I have no hope for the definitive edition as it uses an entirely new asset, and there sadly is absolutely no way to legally acquire the original gold edition online. Amazon sells it for an unfortunate price of $80, which is what it went for in 2001 if my childhood memory serves me right.

As such, onwards with the trial assets.  Attached is a small group of men at arms defending their town, using only the trial demo assets:

![2020-03-11-145039_1366x768_scrot](https://user-images.githubusercontent.com/7000616/76479321-9ef9c700-63c8-11ea-9353-a7dafa29ea0a.png)
