### ISSUE TITLE
Support for Windows and other platforms

### ISSUE THREAD

**Issue by Bigbossbro08** [glouw/openempires#2]
I'm trying to make openempires code to be able to run on Windows but I'm failing because it's Native to Linux. Is there any plans to make openempires cross-platform or Windows support?

**Comment by glouw** [comment]
Should work, the .c files in /src can be compiled with a C++11 or C99 compiler using either clang/gcc/mingw/MSVC.

If you are using MSVC, try importing the src/ folder into MSVC and hitting compile. You will need the SDL2 development libraries for MSVC to link the final binary (labeled as -VC in the urls), which can be found here:

https://www.libsdl.org/download-2.0.php.
https://www.libsdl.org/projects/SDL_net/
https://www.libsdl.org/projects/SDL_ttf/

**Comment by Bigbossbro08** [comment]
There is an error and this behaviour seemingly supportive to Linux only. Windows doesn't support <sys/time.h>

**Comment by Bigbossbro08** [comment]
I found a fix as well. Think I'll do a new commit with Windows and Linux side fix...

**Comment by sandsmark** [comment]
maybe I'm looking at outdated code by now, but I only see an include for `<time.h>`, which should be defined defined in the ISO C standard, so I assume msvc has it available?

**Comment by glouw** [comment]
Could be outdated by now. There have been so many changes as of late I have lost track!
