### ISSUE TITLE
Submit it to Athenaeum

### ISSUE THREAD

**Issue by ghost** [glouw/openempires#3]
this will make the game more discoverable to new users

https://gitlab.com/librebob/athenaeum

https://riot.im/app/#/room/#athenaeum:matrix.org

**Comment by glouw** [comment]
Something like this is for sure on the horizon. I have a list of of things that need doing - the game is not entirely in a playable state, although its an excellent tech demo.

I have a date set for myself to have a fully playable multiplayer client (an MVP of sorts) by the end of April. I will seriously consider something like Athenaeum at that time.
